version: "3.9"

services:
    angular:
        build:
            context: ./angular-question
        container_name: angular-question
        restart: always
        ports:
            - "4200:4200"
        volumes:
            - ./angular-question:/app
        working_dir: /app
        environment:
            - NODE_ENV=development
        networks:
            - course-project

    node:
        build:
            context: ./node-courses
        container_name: node-courses
        restart: always
        ports:
            - "5050:5050"
        volumes:
            - ./node-courses:/app
        working_dir: /app
        environment:
            - NODE_ENV=development
            - DB_URI=mongodb://mongo:27017/courses
        depends_on:
            - mongo
        networks:
            - course-project

    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./mongo:/data/db
        networks:
            - course-project
        environment:
            MONGO_DATA_DIR: /data/db
            MONGO_LOG_DIR: /dev/null
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 3^9r4$f$o7k*TSk9rJBWbh
            MONGO_INITDB_DATABASE: courses

networks:
    course-project:
        driver: bridge
